# Generated by Django 4.2 on 2023-04-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='trait',
            new_name='traits',
        ),
    ]
