# Generated by Django 4.2.7 on 2023-12-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not informed', 'Not Informed')], default='Not informed', max_length=20),
        ),
    ]
