# Generated by Django 4.1.7 on 2023-04-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0004_remove_trait_pet_alter_trait_created_at"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="trait",
            field=models.ManyToManyField(related_name="pets", to="traits.trait"),
        ),
    ]
