# Generated by Django 4.2 on 2023-04-07 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("traits", "0001_initial"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pets",
            new_name="Pet",
        ),
    ]
