# Generated by Django 5.0 on 2023-12-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_pet_group_pet_traits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_group',
            new_name='group',
        ),
    ]
