# Generated by Django 4.2 on 2023-04-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_trait_pet_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Informed', 'Default')], default='Not Informed', max_length=20),
        ),
    ]
