# Generated by Django 4.2 on 2023-04-05 02:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_alter_pet_sex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="group",
        ),
    ]
