# Generated by Django 4.2 on 2023-04-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_group_alter_pet_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='traits',
        ),
    ]
