# Generated by Django 4.1.7 on 2023-04-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="pets",
            field=models.ManyToManyField(related_name="trait", to="pets.pet"),
        ),
    ]
