# Generated by Django 4.1.7 on 2023-04-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0003_trait_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="pet",
        ),
        migrations.AlterField(
            model_name="trait",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
