# Generated by Django 4.2 on 2023-04-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_remove_pet_traits'),
        ('traits', '0003_remove_trait_pets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='name',
            new_name='trait_name',
        ),
        migrations.AddField(
            model_name='trait',
            name='pets',
            field=models.ManyToManyField(related_name='traits', to='pets.pet'),
        ),
    ]
