# Generated by Django 4.2 on 2023-04-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0005_rename_trait_name_trait_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='pets',
        ),
    ]
