# Generated by Django 4.2 on 2023-04-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0006_remove_trait_pets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='name',
            new_name='traits_name',
        ),
    ]
