# Generated by Django 4.2 on 2023-04-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0007_rename_name_trait_traits_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='traits_name',
            new_name='name',
        ),
    ]
