# Generated by Django 4.2 on 2023-04-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0008_rename_traits_name_trait_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='name',
            new_name='trait_name',
        ),
    ]
