# Generated by Django 5.0 on 2023-12-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='pet',
        ),
    ]
